/**
 * Git4u.Common.Web
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Git4ucommonweb);
  }
}(this, function(expect, Git4ucommonweb) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Git4ucommonweb.LoginResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoginResponse', function() {
    it('should create an instance of LoginResponse', function() {
      // uncomment below and update the code to test LoginResponse
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be.a(Git4ucommonweb.LoginResponse);
    });

    it('should have the property accessToken (base name: "AccessToken")', function() {
      // uncomment below and update the code to test the property accessToken
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property accountRoleType (base name: "AccountRoleType")', function() {
      // uncomment below and update the code to test the property accountRoleType
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property formStatus (base name: "FormStatus")', function() {
      // uncomment below and update the code to test the property formStatus
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property rejectReason (base name: "RejectReason")', function() {
      // uncomment below and update the code to test the property rejectReason
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property resultCode (base name: "ResultCode")', function() {
      // uncomment below and update the code to test the property resultCode
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be();
    });

    it('should have the property resultMessage (base name: "ResultMessage")', function() {
      // uncomment below and update the code to test the property resultMessage
      //var instane = new Git4ucommonweb.LoginResponse();
      //expect(instance).to.be();
    });

  });

}));
