/**
 * Git4u.Common.Web
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LoginResponse', 'model/LoginRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/LoginResponse'), require('../model/LoginRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Git4ucommonweb) {
      root.Git4ucommonweb = {};
    }
    root.Git4ucommonweb.APIAccountApi = factory(root.Git4ucommonweb.ApiClient, root.Git4ucommonweb.LoginResponse, root.Git4ucommonweb.LoginRequest);
  }
}(this, function(ApiClient, LoginResponse, LoginRequest) {
  'use strict';

  /**
   * APIAccount service.
   * @module api/APIAccountApi
   * @version 0.0.1
   */

  /**
   * Constructs a new APIAccountApi. 
   * @alias module:api/APIAccountApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the aPI001AccountLogin operation.
     * @callback module:api/APIAccountApi~aPI001AccountLoginCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LoginResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 登入指定的帳號
     * @param {module:model/LoginRequest} loginRequest 登入指定帳號的請求訊息
     * @param {module:api/APIAccountApi~aPI001AccountLoginCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LoginResponse}
     */
    this.aPI001AccountLogin = function(loginRequest, callback) {
      var postBody = loginRequest;

      // verify the required parameter 'loginRequest' is set
      if (loginRequest == undefined || loginRequest == null) {
        throw "Missing the required parameter 'loginRequest' when calling aPI001AccountLogin";
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = LoginResponse;

      return this.apiClient.callApi(
        '/api/API001Account/Login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
