/**
 * Git4u.Common.Web
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Git4ucommonweb) {
      root.Git4ucommonweb = {};
    }
    root.Git4ucommonweb.LoginRequest = factory(root.Git4ucommonweb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoginRequest model module.
   * @module model/LoginRequest
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>LoginRequest</code>.
   * 登入指定帳號的請求訊息
   * @alias module:model/LoginRequest
   * @class
   * @param system {module:model/LoginRequest.SystemEnum} 取得或設定系統商
   * @param account {String} 取得或設定帳號名稱
   * @param email {String} 取得或設定電子郵件位址
   */
  var exports = function(system, account, email) {
    var _this = this;

    _this['System'] = system;
    _this['Account'] = account;
    _this['Email'] = email;
  };

  /**
   * Constructs a <code>LoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginRequest} obj Optional instance to populate.
   * @return {module:model/LoginRequest} The populated <code>LoginRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('System')) {
        obj['System'] = ApiClient.convertToType(data['System'], 'Integer');
      }
      if (data.hasOwnProperty('Account')) {
        obj['Account'] = ApiClient.convertToType(data['Account'], 'String');
      }
      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
    }
    return obj;
  }

  /**
   * 取得或設定系統商
   * @member {module:model/LoginRequest.SystemEnum} System
   */
  exports.prototype['System'] = undefined;
  /**
   * 取得或設定帳號名稱
   * @member {String} Account
   */
  exports.prototype['Account'] = undefined;
  /**
   * 取得或設定電子郵件位址
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;


  /**
   * Allowed values for the <code>System</code> property.
   * @enum {Integer}
   * @readonly
   */
  exports.SystemEnum = {
    /**
     * value: 0
     * @const
     */
    "0": 0,
    /**
     * value: 1
     * @const
     */
    "1": 1,
    /**
     * value: 2
     * @const
     */
    "2": 2,
    /**
     * value: 3
     * @const
     */
    "3": 3,
    /**
     * value: 4
     * @const
     */
    "4": 4,
    /**
     * value: 5
     * @const
     */
    "5": 5,
    /**
     * value: 6
     * @const
     */
    "6": 6,
    /**
     * value: 7
     * @const
     */
    "7": 7,
    /**
     * value: 8
     * @const
     */
    "8": 8,
    /**
     * value: 9
     * @const
     */
    "9": 9,
    /**
     * value: 10
     * @const
     */
    "10": 10,
    /**
     * value: 11
     * @const
     */
    "11": 11,
    /**
     * value: 12
     * @const
     */
    "12": 12,
    /**
     * value: 14
     * @const
     */
    "14": 14  };


  return exports;
}));


