/**
 * Git4u.Common.Web
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Git4ucommonweb) {
      root.Git4ucommonweb = {};
    }
    root.Git4ucommonweb.LoginResponse = factory(root.Git4ucommonweb.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LoginResponse model module.
   * @module model/LoginResponse
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>LoginResponse</code>.
   * 登入指定帳號的回傳資訊
   * @alias module:model/LoginResponse
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>LoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginResponse} obj Optional instance to populate.
   * @return {module:model/LoginResponse} The populated <code>LoginResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('AccessToken')) {
        obj['AccessToken'] = ApiClient.convertToType(data['AccessToken'], 'String');
      }
      if (data.hasOwnProperty('AccountRoleType')) {
        obj['AccountRoleType'] = ApiClient.convertToType(data['AccountRoleType'], 'Integer');
      }
      if (data.hasOwnProperty('FormStatus')) {
        obj['FormStatus'] = ApiClient.convertToType(data['FormStatus'], 'Integer');
      }
      if (data.hasOwnProperty('RejectReason')) {
        obj['RejectReason'] = ApiClient.convertToType(data['RejectReason'], 'String');
      }
      if (data.hasOwnProperty('ResultCode')) {
        obj['ResultCode'] = ApiClient.convertToType(data['ResultCode'], 'String');
      }
      if (data.hasOwnProperty('ResultMessage')) {
        obj['ResultMessage'] = ApiClient.convertToType(data['ResultMessage'], 'String');
      }
    }
    return obj;
  }

  /**
   * 取得或設定 AccessToken
   * @member {String} AccessToken
   */
  exports.prototype['AccessToken'] = undefined;
  /**
   * 取得或設定帳號類型
   * @member {module:model/LoginResponse.AccountRoleTypeEnum} AccountRoleType
   */
  exports.prototype['AccountRoleType'] = undefined;
  /**
   * 取得或設定帳號的表單狀態
   * @member {module:model/LoginResponse.FormStatusEnum} FormStatus
   */
  exports.prototype['FormStatus'] = undefined;
  /**
   * 取得或設定退件原因
   * @member {String} RejectReason
   */
  exports.prototype['RejectReason'] = undefined;
  /**
   * @member {String} ResultCode
   */
  exports.prototype['ResultCode'] = undefined;
  /**
   * @member {String} ResultMessage
   */
  exports.prototype['ResultMessage'] = undefined;


  /**
   * Allowed values for the <code>AccountRoleType</code> property.
   * @enum {Integer}
   * @readonly
   */
  exports.AccountRoleTypeEnum = {
    /**
     * value: 0
     * @const
     */
    "0": 0,
    /**
     * value: 1
     * @const
     */
    "1": 1,
    /**
     * value: 11
     * @const
     */
    "11": 11  };

  /**
   * Allowed values for the <code>FormStatus</code> property.
   * @enum {Integer}
   * @readonly
   */
  exports.FormStatusEnum = {
    /**
     * value: 1
     * @const
     */
    "1": 1,
    /**
     * value: 2
     * @const
     */
    "2": 2,
    /**
     * value: 3
     * @const
     */
    "3": 3,
    /**
     * value: 4
     * @const
     */
    "4": 4,
    /**
     * value: 5
     * @const
     */
    "5": 5,
    /**
     * value: 99
     * @const
     */
    "99": 99,
    /**
     * value: 100
     * @const
     */
    "100": 100  };


  return exports;
}));


